### ISSUE TITLE
watch task not works with 'layouts'

### ISSUE THREAD

**Issue by lethee** [pismute/gulp-makdoc#1]
with running 'gulp watch', modification of 'layouts/defaults.html.hbs' is not applied. 'livereload' not works, 'reload in browser' not works.

**Comment by pismute** [comment]
As of now, the modified file only will be reloaded because I am thinking of performance. When any partial or layout are modified, all files should be rebuilt. I am worrying that reloading all files would make your system take off.

My solutions are:
1. Reload only a modified file as is.
2. Rebuild without documents(`app/docs`).

Any idea?

**Comment by lethee** [comment]
I think solution 1 be OK.
