### ISSUE TITLE
.jshintrc must be required.

### ISSUE THREAD

**Issue by lethee** [pismute/gulp-makdoc#3]
there's error if gulp server, gulp watch without .jshintrc.

make .jshintrc optional.

**Comment by pismute** [comment]
:+1: :heart: 

IMO, If `.jshintrc` is optional, makdoc truely should not require `gulp-jshint`. Currently, the module is hardcoded so that user must always add it. In other to truely remove the dependency we must test whether `gulp-jshintrc` module exists and `.jshintrc` file exists.

I am considering a conditional require module extending https://github.com/jackfranklin/gulp-load-plugins

**Comment by pismute** [comment]
Makdoc don't require a gulp plugin if there not exists. If you want to opt `.jshintrc`, drop `gulp-jshint` module in dependencies. Makdoc only require the gulp plugin that is found.
